[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "octocheese"
version = "0.3.0"
description = "ðŸ™ ðŸ§€ â€“ Copy PyPI Packages to GitHub Releases"
readme = "README.rst"
keywords = [ "github", "github-action", "pypi",]
dynamic = []
dependencies = [
    "apeye>=0.3.0",
    "click>=7.1.2",
    "consolekit>=0.8.2",
    "domdf-python-tools>=1.5.0",
    "dulwich!=0.20.7,!=0.20.8,>=0.20.5",
    "github3-py>=1.3.0",
    "github3-utils>=0.3.0",
    "shippinglabel>=0.6.1",
    "typing-extensions>=3.7.4.3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities",
    "Typing :: Typed",
]
requires-python = ">=3.6"

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/octocheese"
"Issue Tracker" = "https://github.com/domdfcoding/octocheese/issues"
"Source Code" = "https://github.com/domdfcoding/octocheese"
Documentation = "https://octocheese.readthedocs.io/en/latest"

[project.scripts]
octocheese = "octocheese.__main__:main"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "LGPL-3.0-or-later"

[tool.mkrecipe]
conda-channels = [ "domdfcoding",]
extras = "all"
