[tool.poetry]
name = "aiodog.py"
version = "0.2.0"
description = "An async wrapper for https://pypi.org/projects/dog.py which covers all of https://thedogapi.com/"
authors = ["ToxicKidz <78174417+ToxicKidz@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include  = "aiodog" }
]

[tool.poetry.dependencies]
python = ">=3.6"
requests = "^2.25.1"
"dog.py" = "^0.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
